name: instagram_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.2
  flutter_bloc: ^7.3.3
  font_awesome_flutter: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_white.png
    - assets/images/p_1.jpeg
    - assets/images/p_2.jpeg
    - assets/images/p_3.jpeg
    - assets/images/p_4.jpeg
    - assets/images/p_5.jpeg
    - assets/images/p_6.jpeg
    - assets/images/p_7.jpeg
    - assets/images/fp_1.jpg
    - assets/images/fp_2.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-B
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-M
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-L
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf